### ISSUE TITLE
Add E2E tests as a GitHub workflow action

### ISSUE THREAD

**Issue by rafaelzaleski** [woocommerce/woocommerce-gateway-stripe#2530]
As part of our continuous integration and delivery process, we want to ensure that our application is working as expected before merging any pull request. To accomplish this, we will add E2E testing as a GitHub workflow action that will run automatically for every pull request. 

This will help us catch any bugs or issues early on, and ensure that our application is stable and reliable. 

**Tasks:**
- [ ] Modify the E2E setup to work in the CI (it's now focused on a JN site)
- [ ] Create a new GitHub workflow file in the repository
- [ ] Add a new job to the workflow that runs the E2E tests
- [ ] Configure the workflow to run automatically for every PR
- [ ] Verify that the E2E tests are running correctly on every PR
