### ISSUE TITLE
Link enablement (default on)

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2857]
This epic groups the issues for deprecating API Keys Sharing in the extension.
```[tasklist]
### Issues
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2523
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2481
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2437
```
