### ISSUE TITLE
EU Card Brand Choice

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#3001]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2844
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3011
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3015
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3016
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3017
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3031
- [ ] https://github.com/woocommerce/woocommerce/pull/45903
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3059
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3102
```
