### ISSUE TITLE
Payment methods - Add BNPL

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#3003]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3043
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3044
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3045
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3088
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3090
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3094
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3095
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3096
```
```[tasklist]
### Non-critical tasks
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3089
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3097
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3101
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3060
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3112
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3121
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3087
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3070
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3111
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3085
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3086
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3118
```

**Comment by a-danae** [comment]
Related requests in the Stripe extension's feature request board:
- [Accept all major debit and credit cards as well as local payment methods with Stripe](https://woocommerce.com/feature-request/add-afterpay-and-klarna-to-the-list-of-payment-methods/)
- [Include Klarna as part of the Stripe payment gateway](https://woocommerce.com/feature-request/include-klarna-as-part-of-the-stripe-payment-gateway/)
- [Afterpay / Clearpay](https://woocommerce.com/feature-request/afterpay-clearpay/)
