### ISSUE TITLE
Payment methods - Add Wallets

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#3004]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3130
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3131
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3145
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3152
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3155
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3170
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3179
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3199
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3198
```

**Comment by supermagnus** [comment]
Also include Mobilepay in this:
[Wallets] Accept MobilePay payments: https://docs.stripe.com/payments/mobilepay
