### ISSUE TITLE
[BNPL] Accept Klarna payments

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3043]
Allow shoppers to pay with [Klarna](https://docs.stripe.com/payments/klarna).

This payment method _isn't_ available on the Legacy checkout experience.

### Acceptance criteria

- [x] Display this payment method under the Settings page. Scenarios to take into account:
  - [ ] ~When the payment method isn't available for the Stripe account country~ - Desired behavior to be defined https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3070
  - [x] When the store currency isn't supported by the payment method
  - [x] When the transaction isn't a domestic one - Klarna [limitations details](https://docs.stripe.com/payments/klarna#:~:text=The%20following%20tabs%20capture%20Klarna%E2%80%99s%20properties%20and%20country%20availability)
  - [ ] ~Cross-border payments for the EEA, UK, and Switzerland - Klarna [details](https://docs.stripe.com/payments/klarna#:~:text=If%20you%E2%80%99re%20based%20in%20the%20EEA%2C%20UK%2C%20or%20Switzerland)~ - To be handled in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3096
- [x] Display this payment method to shoppers. It must be displayed on
  - [x] The shortcode checkout
  - [x] The block checkout
  - [x] The pay for order page
- [x] Process payments when using this payment method. Confirm that the order is successfully placed and the payment intent has the expected information. Confirm all the options Klarna provides work as expected:
  - [x] Pay now
  - [x] Pay later
  - [x] Pay with financing (Needs an expensive order to be enabled)
- [ ] ~Handle [separate authorization and capture](https://docs.stripe.com/payments/klarna/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#manual-capture)~ - To be handled in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3086
- [x] Handle [denied transactions](https://docs.stripe.com/payments/klarna/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#testmode-guide)
  - [x] The shortcode checkout
  - [ ] ~The block checkout~ - To be handled in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3060
  - [ ] ~The pay for order page~ - To be handled in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3066
- [x] Handle [failed payments](https://docs.stripe.com/payments/klarna/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#web-failed-payments)
- [x] Handle [post-payment events](https://docs.stripe.com/payments/klarna/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#web-fulfillment) if necessary
- [ ] ~Handle [supported locales](https://docs.stripe.com/payments/klarna/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#supported-locales-and-currencies) for shoppers. [API ref](https://docs.stripe.com/payments/klarna/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#customize-klarna-payment-page)~ - To be handled in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3087
- [x] Handle [transaction limits](https://docs.stripe.com/payments/buy-now-pay-later#product-support)
- [x] Handle refunds
  - [x] Partial refunds
  - [x] Full refunds
