### ISSUE TITLE
[BNPL] Accept Affirm payments

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3044]
Allow shoppers to pay with [Affirm](https://docs.stripe.com/payments/affirm).

This payment method isn't available on the Legacy checkout experience.

### Acceptance criteria

- [ ] Display this payment method under the Settings page. Scenarios to take into account:
  - [ ] When the payment method isn't available for the Stripe account country
  - [ ] When the store currency isn't supported by the payment method
- [ ] Display this payment method to shoppers. It must be displayed on
  - [ ] The shortcode checkout
  - [ ] The block checkout
  - [ ] The pay for order page
- [ ] Process payments when using this payment method. Confirm that the order is successfully placed and the payment intent has the expected information. Confirm all the options [Affirm provides](https://docs.stripe.com/payments/affirm#payment-options) work as expected:
  - [ ] Pay in 4
  - [ ] Monthly Installments
- [x] ~Handle [separate authorization and capture](https://docs.stripe.com/payments/affirm/accept-a-payment?payment-ui=direct-api#manual-capture)~ - To be handled in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3086
- [ ] Handle [failed payments](https://docs.stripe.com/payments/affirm/accept-a-payment?payment-ui=direct-api#failed-payments)
  - [ ] The shortcode checkout
  - [ ] The block checkout - Likely not working as expected. See https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3060
  - [ ] The pay for order page - Likely not working as expected. See https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3066
- [ ] Handle [post-payment events](https://docs.stripe.com/payments/affirm/accept-a-payment?payment-ui=direct-api#post-payment-events) if necessary
- [ ] Handle [supported currencies](https://docs.stripe.com/payments/affirm#prohibited-and-restricted-business-categories:~:text=Presentment%20currency) for shoppers
- [ ] Handle refunds
  - [ ] Partial refunds
  - [ ] Full refunds

Note: Pre-orders is a [category prohibited](https://docs.stripe.com/payments/affirm#prohibited-and-restricted-business-categories) for this payment method. We may want to add a limitation for our compatibility with the Pre-orders extension
