### ISSUE TITLE
[BNPL] Accept Afterpay payments

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3045]
Allow shoppers to pay with [Afterpay](https://docs.stripe.com/payments/afterpay-clearpay).

This payment method isn't available on the Legacy checkout experience.

### Acceptance criteria

- [x] Display this payment method under the Settings page. Scenarios to take into account:
  - [x] When the payment method isn't available for the [Stripe account country](https://docs.stripe.com/payments/afterpay-clearpay#collection-schedule:~:text=Stripe%20accounts%20in%20the%20following%20countries)
  - [x] When the [store currency](https://docs.stripe.com/payments/afterpay-clearpay#collection-schedule:~:text=Presentment%20currency,AUD%2C%20or%20NZD) isn't supported by the payment method
  - [x] When the Stripe account is from the UK - It must display Clearpay label and icon
  - [x] When the Stripe is from anywhere else - It must display Afterpay label and icon
- [x] Display this payment method to shoppers. Displaying Clearpay for UK Stripe accounts and Afterpay for the rest. It must be displayed on
  - [x] The shortcode checkout
  - [x] The block checkout
  - [x] The pay for order page
- [x] Process payments when using this payment method. Confirm that the order is successfully placed and the payment intent has the expected information. ~Confirm all the options [Afterpay provides](https://docs.stripe.com/payments/afterpay-clearpay#collection-schedule) work as expected~ The test flow is redirect one, it doesn't let you choose between these options:
  - [x] ~Pay in 4~
  - [x] ~Monthly Installments~
- [x] ~Handle [separate authorization and capture](https://docs.stripe.com/payments/afterpay-clearpay/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#manual-capture)~ - To be addressed in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3086
- [x] Handle [failed payments](https://docs.stripe.com/payments/afterpay-clearpay/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#web-failed-payments)
  - [x] The shortcode checkout
  - [x] The block checkout - Likely not working as expected. See https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3060
  - [x] The pay for order page - Likely not working as expected. See https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3066
- [x] Handle [post-payment events](https://docs.stripe.com/payments/afterpay-clearpay/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#web-fulfillment) if necessary
- [x] Handle [supported currencies](https://docs.stripe.com/payments/afterpay-clearpay/accept-a-payment?web-or-mobile=web&payments-ui-type=stripe-hosted#compatibility) for shoppers
- [x] Handle [transaction limits](https://docs.stripe.com/payments/afterpay-clearpay#collection-schedule)
- [x] Handle refunds
  - [x] Partial refunds
  - [x] Full refunds

Note: Pre-orders is a [category prohibited](https://docs.stripe.com/payments/afterpay-clearpay#prohibited-business-categories) for this payment method. We may want to add a limitation to our compatibility with the pre-orders extension. We could handle this in a separate task.
