### ISSUE TITLE
[Wallets] Cash App Payments - Add subscription support

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-stripe#3155]
Allow shoppers to pay with [CashApp](https://docs.stripe.com/payments/cash-app-pay) when purchasing subscription products. 

```[tasklist]
### Tasks
- [x] Purchase simple subscriptions.
- [ ] ~~Purchase free trial subscriptions.~~ https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3171
- [x] Process renewal orders.
- [x] Pay for failed renewals manually.
- [x] Renew a subscription early.
- [ ] _Optional_. Add payment method via my account. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3179
- [x] View payment method information from customer's view subscription page.
- [x] Add token support - payment methods that support subscriptions need to implement a `WC_Payment_Token`.
```

**Comment by james-allan** [comment]
Fixed via #3156. The remaining issues of free trials and the my account tokens have been filed under separate issues. Those issues have been referenced in the task list above in the issue description.
