### ISSUE TITLE
Deprecate Key Sharing - Webhook setup via API

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#3195]
```[tasklist]
### Tasks
- [x] Add function to `WC_REST_Stripe_Account_Keys_Controller` capable of generating webhook secret
- [x] Update account key settings modal to no longer include input, replace with a button for automatic generating
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3213
- [x] Fix what happens when you unset the public and secret key (disconnect), the webhook secret stay "enabled" - https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3221
```

**Comment by james-allan** [comment]
Just dropping some initial notes: 

The Webhook APIs can be found here: https://docs.stripe.com/api/webhook_endpoints

I've mocked up what I think these UIs may look like. 

| Not configured | Configured |
|--------|--------|
| <img width="548" alt="Screenshot 2024-06-13 at 2 45 45 PM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/6b32c293-4153-4a39-b0bf-c4af889c409b"> | <img width="552" alt="Screenshot 2024-06-13 at 3 04 58 PM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/a3bd067b-fede-42bc-bfc5-2f260d1a4960">| 


A couple of additional thoughts, I think we will want to store the webhook ID in the stripe settings. This is for a couple of reasons: 

1. It will enable us to automatically update the webhook if we need to start listening to new events. 
2. It will allow us to delete the webhook. This may be useful when you click the reconfigure button so we don't end up creating lots of webhooks.
