### ISSUE TITLE
Webhooks - Improve handling webhook events

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3327]
This epic is intended to group all the issues around processing webhook events.

### Why having an epic?
- We have many reports around duplicated order notes, emails, and inventory reductions.
- We haven't been able to replicate the problem. We've tried multiple times, and we've dived deeply into the processing flow.
We have multiple issues and scattered information related to processing webhook events. Grouping all we know about this problem in a single place facilitates a better understanding of it.

## Duplicated notes / emails / inventory reduction

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3273
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2536
```

### What we know
- A merchant that experienced the issue confirmed they can't replicate it when using a test account. This could explain why we haven't been able to replicate. Ref: [#](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issue-1421874734)
- A merchant that experiences the issue confirmed they have a single webhook endpoint configured for the site URL. Ref: [#](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-2230631236), [#](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-2239746053)
- The behavior is only present when the Legacy checkout experience is disabled. Ref: [#](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-2256651863), [#](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-2254866944), [#](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-2236455325), [#](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-1212925245), [#](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-1108954903)

### Results from previous efforts diving into this
- From Hector Lovo - `WC_Stripe_Payment_Gateway->process_response()` is being called twice. [Ref](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-1111361275)

## Other improvements

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3326
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3328
```

**Comment by a-danae** [comment]
The fix was released in 8.6.1 🎉  Marking this Epic as closed.
