### ISSUE TITLE
Migrate from PRB to ECE

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#3381]
```[tasklist]
### Milestone 0
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3401
```

```[tasklist]
### Milestone 1
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3402
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3403
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3404
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3469
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3470
```

```[tasklist]
### Milestone 2
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3408
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3409
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3410
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3411
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3412
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3471
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3472
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3491
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3499
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3534
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3536
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3544
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3578
```

```[tasklist]
### Milestone 3
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3405
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3406
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3521
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3479
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3598
```

```[tasklist]
### Milestone 4
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3407
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3590
- [ ] https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3591
```

**Comment by Mayisha** [comment]
The express checkout element has been implemented for the new checkout experience. Closing this issue.
