### ISSUE TITLE
Move from Link Autofill Modal to Link in the Payment Element

### ISSUE THREAD

**Issue by annemirasol** [woocommerce/woocommerce-gateway-stripe#3611]
```[tasklist]
### Tasks
- [x] [Remove Link Autofill modal](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3612)
- [x] [Improve Link in the Payment Element for Block Checkout](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3619)
- [x] [Improve Link in the Payment Element for Classic (Shortcode) Checkout](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3619)
- [x] Link in the Payment Element and subscriptions (recurring payments (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3633, https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3577)
- [x] Link in the Payment Element and saved payment methods
```
